name: update-companies-data

on:
  schedule:
    # Runs at 18:45 (Nepal Time), every Monday to Friday
    - cron: "0 13,14,15,16,17 * * 0,1,2,3,4,5"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./src

jobs:
  update-daily-data:
    name: update-daily-data
    runs-on: ubuntu-latest
    
    # Explicitly grant the workflow permission to write to the repository
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install packages
        run: pip install -r requirements.txt

      - name: Discover new companies
        run: python discoverCompanies.py

      - name: Backfill data for new companies
        run: python allDataScrapper.py

      - name: Run daily updater
        run: python dailyDataScrapper.py

      - name: Run Nepse Index updater
        run: python scripts/update_nepse_index.py      

      - name: Commit and Push Changes
        run: |
          git config --local user.email "aabishkar2@gmail.com"
          git config --local user.name "Aabishkar Wagle Bot"
          
          # Stage changes in the data directory
          git add ../data
          
          # Commit if there are changes, otherwise gracefully skip
          git commit -m "Update data and sync new companies" || echo "No changes to commit"
          
          # Push using the built-in authentication set up by actions/checkout
          git push
